export const THEME = {
  section: 'Оформление',
  theme: {
    name: 'Тема',
    value: 'MAIN_THEME',
    _key: 'Theme',
  },
  currentTheme: 'MAIN_THEME',
  MAIN_THEME: {
    BACKGROUNDCOLOR_LG: ['#30cfd0', '#146185', '#30cfd0'],
    BACKGROUNDCOLOR_LG_Disabled: ['#146185', '#197098', '#146185'],
    BACKGROUNDCOLOR: '#30cfd0',
    NO_ACTIVE: '#146185',
    TEXT_COLOR: 'white',
    ITEM_COLOR: 'white',
    DANGER_COLOR: '#d81b60',
    name: 'MAIN_THEME',
  },
  LIGHT_THEME: {
    BACKGROUNDCOLOR_LG: ['#efefef', '#cccccc', '#efefef'],
    BACKGROUNDCOLOR_LG_Disabled: ['#efefef', '#cccccc', '#efefef'],
    BACKGROUNDCOLOR: '#efefef',
    NO_ACTIVE: '#cccccc',
    TEXT_COLOR: 'black',
    ITEM_COLOR: 'black',
    DANGER_COLOR: '#d81b60',
    name: 'LIGHT_THEME',
  },
  DARK_THEME: {
    BACKGROUNDCOLOR_LG: ['#777777', '#111111', '#777777'],
    BACKGROUNDCOLOR_LG_Disabled: ['#777777', '#111111', '#777777'],
    BACKGROUNDCOLOR: '#777777',
    NO_ACTIVE: '#111111',
    TEXT_COLOR: 'white',
    ITEM_COLOR: 'white',
    DANGER_COLOR: '#d81b60',
    name: 'DARK_THEME',
  },
  MAIN_BUTTONS_BORDERRADIUS: 25,
  MAIN_BACKGROUNDSTYLES: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  TITLE_FONT: { fontSize: 20, fontWeight: 'bold', fontFamily: 'open-bold' },
  TEXT_FONT: { fontSize: 16, fontFamily: 'open-regular' },
  SHADOW_FOR_IOS: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
  },
  // SCREEN_OPTIONS: {
  //   headerStyle: {
  //     backgroundColor: '#30cfd0',
  //   },
  //   headerTintColor: '#fff',
  // },
};
