export const CONST = {
  ratioScreen: 85,
  profileName: 'User',
  HEADER_OPTIONS: {
    mainBackground: false,
    drawerIcon: 'menu',
    settingsIcon: 'md-settings-sharp',
    notificationsIcon: 'notifications',
    home: 'home',
    newmoving: 'clipboard-arrow-right-outline',
    newreceipt: 'library-add',
    database: 'database',
    report: 'pie-chart',
    back: 'arrow-back-ios',
    backgroundColor: ['#30cfd0', '#146185'],
  },
  firebaseConfig: {
    apiKey: 'AIzaSyAvYSioiBQ-_r85JpC5qriziK95MMfgM0A',
    authDomain: 'warehouse-6b821.firebaseapp.com',
    databaseURL: 'https://warehouse-6b821-default-rtdb.firebaseio.com',
    projectId: 'warehouse-6b821',
    storageBucket: 'warehouse-6b821.appspot.com',
    messagingSenderId: '161171585310',
    appId: '1:161171585310:web:a5dfa1c17a68e5efb4f10f',
    measurementId: 'G-Y8SZ338KVW',
  },
};
